/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef example_TYPES_H
#define example_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>


namespace example {

class Person;

typedef struct _Person__isset {
  _Person__isset() : id(false), name(false), age(false) {}
  bool id :1;
  bool name :1;
  bool age :1;
} _Person__isset;

class Person : public virtual ::apache::thrift::TBase {
 public:

  Person(const Person&);
  Person& operator=(const Person&);
  Person() : id(0), name(), age(0) {
  }

  virtual ~Person() noexcept;
  int32_t id;
  std::string name;
  int32_t age;

  _Person__isset __isset;

  void __set_id(const int32_t val);

  void __set_name(const std::string& val);

  void __set_age(const int32_t val);

  bool operator == (const Person & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    if (!(name == rhs.name))
      return false;
    if (!(age == rhs.age))
      return false;
    return true;
  }
  bool operator != (const Person &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Person & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(Person &a, Person &b);

std::ostream& operator<<(std::ostream& out, const Person& obj);

} // namespace

#endif
