/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef PersonService_H
#define PersonService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "example_types.h"

namespace example {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class PersonServiceIf {
 public:
  virtual ~PersonServiceIf() {}
  virtual void ping() = 0;
  virtual void getPerson(Person& _return, const int32_t id) = 0;
};

class PersonServiceIfFactory {
 public:
  typedef PersonServiceIf Handler;

  virtual ~PersonServiceIfFactory() {}

  virtual PersonServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(PersonServiceIf* /* handler */) = 0;
};

class PersonServiceIfSingletonFactory : virtual public PersonServiceIfFactory {
 public:
  PersonServiceIfSingletonFactory(const ::std::shared_ptr<PersonServiceIf>& iface) : iface_(iface) {}
  virtual ~PersonServiceIfSingletonFactory() {}

  virtual PersonServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(PersonServiceIf* /* handler */) {}

 protected:
  ::std::shared_ptr<PersonServiceIf> iface_;
};

class PersonServiceNull : virtual public PersonServiceIf {
 public:
  virtual ~PersonServiceNull() {}
  void ping() {
    return;
  }
  void getPerson(Person& /* _return */, const int32_t /* id */) {
    return;
  }
};


class PersonService_ping_args {
 public:

  PersonService_ping_args(const PersonService_ping_args&);
  PersonService_ping_args& operator=(const PersonService_ping_args&);
  PersonService_ping_args() {
  }

  virtual ~PersonService_ping_args() noexcept;

  bool operator == (const PersonService_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const PersonService_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PersonService_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class PersonService_ping_pargs {
 public:


  virtual ~PersonService_ping_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class PersonService_ping_result {
 public:

  PersonService_ping_result(const PersonService_ping_result&);
  PersonService_ping_result& operator=(const PersonService_ping_result&);
  PersonService_ping_result() {
  }

  virtual ~PersonService_ping_result() noexcept;

  bool operator == (const PersonService_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const PersonService_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PersonService_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class PersonService_ping_presult {
 public:


  virtual ~PersonService_ping_presult() noexcept;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _PersonService_getPerson_args__isset {
  _PersonService_getPerson_args__isset() : id(false) {}
  bool id :1;
} _PersonService_getPerson_args__isset;

class PersonService_getPerson_args {
 public:

  PersonService_getPerson_args(const PersonService_getPerson_args&);
  PersonService_getPerson_args& operator=(const PersonService_getPerson_args&);
  PersonService_getPerson_args() : id(0) {
  }

  virtual ~PersonService_getPerson_args() noexcept;
  int32_t id;

  _PersonService_getPerson_args__isset __isset;

  void __set_id(const int32_t val);

  bool operator == (const PersonService_getPerson_args & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    return true;
  }
  bool operator != (const PersonService_getPerson_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PersonService_getPerson_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class PersonService_getPerson_pargs {
 public:


  virtual ~PersonService_getPerson_pargs() noexcept;
  const int32_t* id;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PersonService_getPerson_result__isset {
  _PersonService_getPerson_result__isset() : success(false) {}
  bool success :1;
} _PersonService_getPerson_result__isset;

class PersonService_getPerson_result {
 public:

  PersonService_getPerson_result(const PersonService_getPerson_result&);
  PersonService_getPerson_result& operator=(const PersonService_getPerson_result&);
  PersonService_getPerson_result() {
  }

  virtual ~PersonService_getPerson_result() noexcept;
  Person success;

  _PersonService_getPerson_result__isset __isset;

  void __set_success(const Person& val);

  bool operator == (const PersonService_getPerson_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const PersonService_getPerson_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PersonService_getPerson_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PersonService_getPerson_presult__isset {
  _PersonService_getPerson_presult__isset() : success(false) {}
  bool success :1;
} _PersonService_getPerson_presult__isset;

class PersonService_getPerson_presult {
 public:


  virtual ~PersonService_getPerson_presult() noexcept;
  Person* success;

  _PersonService_getPerson_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class PersonServiceClient : virtual public PersonServiceIf {
 public:
  PersonServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  PersonServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
  void getPerson(Person& _return, const int32_t id);
  void send_getPerson(const int32_t id);
  void recv_getPerson(Person& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class PersonServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<PersonServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (PersonServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_getPerson(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  PersonServiceProcessor(::std::shared_ptr<PersonServiceIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &PersonServiceProcessor::process_ping;
    processMap_["getPerson"] = &PersonServiceProcessor::process_getPerson;
  }

  virtual ~PersonServiceProcessor() {}
};

class PersonServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  PersonServiceProcessorFactory(const ::std::shared_ptr< PersonServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::std::shared_ptr< PersonServiceIfFactory > handlerFactory_;
};

class PersonServiceMultiface : virtual public PersonServiceIf {
 public:
  PersonServiceMultiface(std::vector<std::shared_ptr<PersonServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~PersonServiceMultiface() {}
 protected:
  std::vector<std::shared_ptr<PersonServiceIf> > ifaces_;
  PersonServiceMultiface() {}
  void add(::std::shared_ptr<PersonServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  void getPerson(Person& _return, const int32_t id) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getPerson(_return, id);
    }
    ifaces_[i]->getPerson(_return, id);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class PersonServiceConcurrentClient : virtual public PersonServiceIf {
 public:
  PersonServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  PersonServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
  void getPerson(Person& _return, const int32_t id);
  int32_t send_getPerson(const int32_t id);
  void recv_getPerson(Person& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
